name: build
on:
  push:
    paths:
      - 'app/**'
      - 'west.yml'
      - 'build.sh'
  workflow_call:
defaults:
  run:
    shell: bash --noprofile --norc -x -e -o pipefail {0}
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Free up some disk space
        run: |
          df -h
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" /usr/local/lib/android /usr/share/dotnet || true
          df -h
      - uses: actions/checkout@v4
      - name: Build
        run: |
          docker run -v $PWD:/workspace/project -w /workspace/project ghcr.io/zephyrproject-rtos/ci:v0.28.4 ./build.sh vatican-cameos
      - uses: actions/upload-artifact@v4
        with:
          path: artifacts/*
